version: '3'
services:
  contour-tileserver:
    image: maptiler/tileserver-gl:v4.5.1
    ports:
      - "8080:8080"
    volumes:
      - ./osm/mbtiles:/data
      - ./config:/config
      - ./styles:/styles
    command: "-c /config/tileserver.json"